server:
  port: 8081

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: "jdbc:oracle:thin:@//HOST:1521/SERVICE"
    username: "YOUR_USERNAME"
    password: "YOUR_PASSWORD"

app:
  logging:
    file-path: ./logs
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
  sample:
    file:
      upload-dir: uploads/sample/files # 서버 경로에 맞춰서 수정필요
  editor:
    image:
      upload-dir: uploads/editor/images # 서버 경로에 맞춰서 수정필요
      download-uri: /cm/editor/image/download/

logging:
  config: classpath:logback-prod.xml
  level:
    root: INFO
    com.shinhan.spp: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    doc-expansion: none # tag, operation 펼치는 방식
    disable-swagger-default-url: true


secret:
  enc:
    salt: e5af6017-fc35-4dd0-9c9e-41b9968f3b0e

jwt:
  secret: "spp-dev-jwt-secret-2026-01-27-8f3a2b1c9d4e7f6a5c0b9a8d7e6f5a4b"