server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lxnn
    username: test
    password: 1234


app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
  auth:
    user-header: "X-User-Id"
  sample:
    file:
      upload-dir: uploads/sample/files
  editor:
    image:
      upload-dir: uploads/editor/images
      download-uri: /cm/editor/image/download/

logging:
  config: classpath:logback-local.xml
  level:
    root: INFO
    com.shinhan.spp: DEBUG


springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    doc-expansion: none # tag, operation 펼치는 방식
    disable-swagger-default-url: true


secret:
  enc:
    salt: e5af6017-fc35-4dd0-9c9e-41b9968f3b0e

jwt:
  secret: "spp-dev-jwt-secret-2026-01-27-8f3a2b1c9d4e7f6a5c0b9a8d7e6f5a4b"